### ISSUE TITLE
framework header not imported correctly

### ISSUE THREAD

**Issue by lorenzoPrimi** [measurement-kit/mkall-ios#1]
The includes in the framework are not correct:
`#include <measurement_kit/common/scalar.hpp>`
is not correct, should be the full path
`#include <libmeasurement_kit/measurement_kit/common/scalar.hpp>`
or relative path
`#include "scalar.hpp"`

Furthermore in the iOS code every include:
`#include <measurement_kit/ffi.h>`
should include the full path (and name) of the new library.
`#include <libmeasurement_kit/measurement_kit/ffi.h>`

**Comment by bassosimone** [comment]
This has now been fixed for quite some time; closing.
